backend:
  name: github
  repo: ota-vr/Jestedsky-vitr
  branch: main
  auth_type: pkce
  app_id: "Ov23liB7NFRE5PIqSJyu"

media_folder: "images/web"
public_folder: "images/web"

collections:
  - name: "aktuality"
    label: "Aktuality (Deníček)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout (Neměnit)", name: "layout", widget: "hidden", default: "default"}
      - {label: "Nadpis aktuality", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Hlavní fotka", name: "image", widget: "image", required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - label: "Fotogalerie (další fotky dole)"
        name: "gallery"
        widget: "list"
        required: false
        field: {label: "Fotka", name: "image", widget: "image"}